#!/bin/sh

wget https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors -O ~/.dir_colors

for symlink in ag editorconfig git mercurial tmux vim nvim ruby zsh alacritty
do
  stow -v -t "$HOME" "$symlink"
done
