theme = "catppuccin_mocha"

[editor]
cursorline = true
color-modes = true
idle-timeout = 150
rulers = [80,100]
bufferline = "always"
auto-pairs = false

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
