#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt flowcontrol
stty -ixon -ixoff 2>/dev/null

unsetopt correctall
cdpath=(. .. ~)

# Customize to your needs...
eval "$(direnv hook zsh)"

[ -z "$TMUX" ] && export TERM="xterm-256color"
export EDITOR="vim"
export VISUAL="vim"
export GOPATH=~/.go-workspace

alias fuck='sudo $(fc -l -n -1)'
alias gst='git status -sb'
