source  /usr/share/zsh-antigen/antigen.zsh

antigen use prezto

antigen bundle chriskempson/base16-shell

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen bundle environment
antigen bundle terminal
antigen bundle editor
antigen bundle history
antigen bundle directory
antigen bundle spectrum
antigen bundle utility
antigen bundle git
antigen bundle ruby
antigen bundle python
antigen bundle node
antigen bundle tmux
antigen bundle ssh
antigen bundle fasd

antigen theme bhilburn/powerlevel9k

antigen apply

##
## Executes commands at the start of an interactive session.
##
## Authors:
##   Sorin Ionescu <sorin.ionescu@gmail.com>
##
#
## Source Prezto.
#if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
#fi
#
#unsetopt flowcontrol
#stty -ixon -ixoff 2>/dev/null
#
#unsetopt correctall
#cdpath=(. .. ~)
#
## Customize to your needs...
#eval "$(direnv hook zsh)"
#
#[ -z "$TMUX" ] && export TERM="xterm-256color"
#export EDITOR="vim"
#export VISUAL="vim"
#export GOPATH=~/Projects/golang
#export PATH=$GOPATH/bin:$PATH
#
#alias fuck='sudo $(fc -l -n -1)'
#alias gst='git status -sb'
#
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#
#load-nvmrc() {
#  if [[ -f .nvmrc && -r .nvmrc ]]; then
#    nvm use
#  fi
#}
#add-zsh-hook chpwd load-nvmrc
