# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="nestor_salceda"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want disable red dots displayed while waiting for completion
# DISABLE_COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
stty -ixon

export TERM="xterm-256color"
export EDITOR="vim"
export PATH=$HOME/bin:$HOME/.rvm/bin:$PATH # Add RVM to PATH for scripting

alias gst='git status -sb'

plugins=(debian git vi-mode mercurial python virtualenvwrapper pip knife zsh-syntax-highlighting tmux rvm)

source $ZSH/oh-my-zsh.sh

cdpath=(. .. ~)
unsetopt correctall
zstyle ":vcs_info:*" enabled git hg
